spring:
  application:
    name: voting-app-service

server:
  port: 8080

cpf_validator:
  url: https://user-info.herokuapp.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

endpoints:
  restart:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream