spring:
  application:
    name: voting-agenda-service
  data:
    mongodb:
      uri: mongodb://mongodb/agenda_db

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

endpoints:
  restart:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream